# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

apt_packages:
  - libgsl-dev

r_packages:
  - pkgdown
  - covr
  
after_success:
  - R CMD INSTALL .
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'

r:
  - oldrel
  - release
  - devel   
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
