# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

apt_packages:
  - gsl-bin

r:
  - devel
  - release
    after_success: Rscript -e 'covr::codecov()'
    before_deploy:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - oldrel
